apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-medical-history
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-medical-history
  template:
    metadata:
      labels:
        app: patient-medical-history
    spec:
      containers:
        - name: app
          image: skatarina/patient-medical-history:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongodb-service:27017/dev
          imagePullPolicy: Always

---
# SERVICE

apiVersion: v1
kind: Service
metadata:
  name: patient-medical-history-service
spec:
  selector:
    app: patient-medical-history
  ports:
    - port: 80
      targetPort: 8080
