version: '3'

services:
  postgresql-master:
    image: 'docker.io/bitnami/postgresql-repmgr:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=my_password
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
      - REPMGR_PRIMARY_HOST=postgresql-master
      - REPMGR_PARTNER_NODES=pg-1,pg-2,pg-0
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_ID=1
      - REPMGR_NODE_NETWORK_NAME=postgresql-master
      - REPMGR_USERNAME=repmgr_user
      - REPMGR_PASSWORD=repmgr_password
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  postgresql-slave:
    image: 'docker.io/bitnami/postgresql-repmgr:latest'
    ports:
      - '5433:5432'
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=my_password
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
      - REPMGR_PRIMARY_HOST=postgresql-master
      - REPMGR_PARTNER_NODES=pg-0,pg-2,pg-1
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_ID=2
      - REPMGR_NODE_NETWORK_NAME=postgresql-slave
      - REPMGR_USERNAME=repmgr_user
      - REPMGR_PASSWORD=repmgr_password
    volumes:
      - 'postgresql_slave_data:/bitnami/postgresql'
    depends_on:
      postgresql-master:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  postgresql-slave2:
    image: 'docker.io/bitnami/postgresql-repmgr:latest'
    ports:
      - '5434:5432'
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=my_password
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
      - REPMGR_PRIMARY_HOST=postgresql-master
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-2
      - REPMGR_NODE_ID=3
      - REPMGR_NODE_NETWORK_NAME=postgresql-slave2
      - REPMGR_USERNAME=repmgr_user
      - REPMGR_PASSWORD=repmgr_password
    volumes:
      - 'postgresql_slave2_data:/bitnami/postgresql'
    depends_on:
      postgresql-master:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  pgpool:
    image: bitnami/pgpool:latest
    ports:
      - '5435:5432'
    environment:
      - PGPOOL_BACKEND_NODES=1:postgresql-master:5432,2:postgresql-slave:5433,3:postgresql-slave2:5434
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_SR_CHECK_USER=repmgr_user
      - PGPOOL_SR_CHECK_PASSWORD=repmgr_password
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=my_password
      - PGPOOL_ADMIN_USERNAME=pgpool_user
      - PGPOOL_ADMIN_PASSWORD=pgpool_password
      - PGPOOL_LOG_LEVEL=DEBUG
    healthcheck:
      test: [ "CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      postgresql-master:
        condition: service_healthy
      postgresql-slave:
        condition: service_healthy
      postgresql-slave2:
        condition: service_healthy

  patient-core-data-service:
    build:
      context: ../PatientCoreData
    container_name: patient-core-data-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pgpool:5432/my_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: my_password
    depends_on:
      pgpool:
        condition: service_healthy
    restart: always


volumes:
  postgresql_master_data:
    driver: local
  postgresql_slave_data:
    driver: local
  postgresql_slave2_data:
    driver: local

