#!/bin/bash
set -e

REPLICATION_USER="replicator"
REPLICATION_PASSWORD="replicator"
psql -U postgres -c "CREATE ROLE $REPLICATION_USER WITH REPLICATION ENCRYPTED PASSWORD '$REPLICATION_PASSWORD' LOGIN;"